nohup stdbuf -oL python3 -u sayari_mapper.py -i "./input/entities-0000*.csv.gz" -o ./output -r ./input/relationships.db -U > runlog0.txt &
nohup stdbuf -oL python3 -u sayari_mapper.py -i "./input/entities-0001*.csv.gz" -o ./output -r ./input/relationships.db -U > runlog1.txt &
nohup stdbuf -oL python3 -u sayari_mapper.py -i "./input/entities-0002*.csv.gz" -o ./output -r ./input/relationships.db -U > runlog2.txt &
nohup stdbuf -oL python3 -u sayari_mapper.py -i "./input/entities-0003*.csv.gz" -o ./output -r ./input/relationships.db -U > runlog3.txt &
nohup stdbuf -oL python3 -u sayari_mapper.py -i "./input/entities-0004*.csv.gz" -o ./output -r ./input/relationships.db -U > runlog4.txt &
nohup stdbuf -oL python3 -u sayari_mapper.py -i "./input/entities-0005*.csv.gz" -o ./output -r ./input/relationships.db -U > runlog5.txt &
nohup stdbuf -oL python3 -u sayari_mapper.py -i "./input/entities-0006*.csv.gz" -o ./output -r ./input/relationships.db -U > runlog6.txt &
nohup stdbuf -oL python3 -u sayari_mapper.py -i "./input/entities-0007*.csv.gz" -o ./output -r ./input/relationships.db -U > runlog7.txt &
nohup stdbuf -oL python3 -u sayari_mapper.py -i "./input/entities-0008*.csv.gz" -o ./output -r ./input/relationships.db -U > runlog8.txt &
nohup stdbuf -oL python3 -u sayari_mapper.py -i "./input/entities-0009*.csv.gz" -o ./output -r ./input/relationships.db -U > runlog9.txt &
